<?php
/**
 * Gets the number of forum posts/comments for this user
 */
function user_postcounts_get_postcount($uid) {
  $result = db_query('SELECT posts FROM {user_postcounts} WHERE uid = %d', $uid);
  if (db_num_rows($result)) {
    return db_result($result);
  }
  else {
    return _user_postcounts_db($uid, 0);
  }
}


function _user_postcounts_db($uid, $delta) {
  if ($delta && db_num_rows(db_query('SELECT uid FROM {user_postcounts} WHERE uid = %d', $uid))) {
    db_query('UPDATE {user_postcounts} SET posts = posts + %d WHERE uid = %d', $delta, $uid);
  }
  else {
    // the hooks are always called after the relevant INSERT/DELETE, so $delta is not relevant here
    $posts = db_result(db_query("SELECT COUNT(nid) FROM {node} n WHERE uid = %d", $uid));
    $posts += db_result(db_query("SELECT COUNT(cid) FROM {comments} c WHERE uid = %d", $uid));
    db_query('INSERT INTO {user_postcounts} (uid, posts) VALUES (%d, %d) ', $uid, $posts);
    return $posts;
  }
}

function user_postcounts_nodeapi($node, $op) {
  _user_postcounts_act($op, is_object($node) ? $node->uid : $node['uid']);
}

function user_postcounts_comment($comment, $op) {
  _user_postcounts_act($op, is_object($comment) ? $comment->uid : $comment['uid']);
}

function _user_postcounts_act($op, $uid) {
  static $deltas = array('insert' => 1, 'delete' => -1);
  if (isset($deltas[(string)$op])) {
    _user_postcounts_db($uid, $deltas[$op]);
  }
}
